# Generated by Django 4.2.17 on 2024-12-28 09:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('course_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=255)),
                ('duration', models.IntegerField()),
                ('start_date', models.DateField()),
                ('deadlinee', models.DateField()),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('lesson_id', models.UUIDField(default=django.db.models.fields.UUIDField, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('lesson_type', models.CharField(choices=[('audio', 'Audio'), ('video', 'Video'), ('text', 'Text')], max_length=10)),
                ('day_number', models.PositiveIntegerField()),
                ('max_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('media_url', models.URLField(blank=True, null=True)),
                ('is_optional', models.BooleanField(default=False)),
                ('start_date', models.DateField()),
                ('deadline', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='courses.courses')),
            ],
        ),
        migrations.CreateModel(
            name='UserCourse',
            fields=[
                ('user_course_id', models.UUIDField(default=django.db.models.fields.UUIDField, editable=False, primary_key=True, serialize=False)),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('completionPercentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('overall_course_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses_enrolled', to='courses.courses')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrolled_users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('quizId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question', models.TextField()),
                ('options', models.JSONField()),
                ('correctAnswer', models.CharField(max_length=255)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='courses.lesson')),
            ],
        ),
        migrations.CreateModel(
            name='LessonScore',
            fields=[
                ('lesson_score_id', models.UUIDField(default=django.db.models.fields.UUIDField, editable=False, primary_key=True, serialize=False)),
                ('score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('completed_at', models.DateTimeField()),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_scores_in_courses', to='courses.lesson')),
                ('user_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_scores', to='courses.usercourse')),
            ],
        ),
    ]
