# Generated by Django 4.2.17 on 2024-12-28 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courses',
            old_name='deadlinee',
            new_name='deadline',
        ),
    ]
