# Generated by Django 4.2.17 on 2024-12-28 09:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('progress_id', models.UUIDField(default=django.db.models.fields.UUIDField, editable=False, primary_key=True, serialize=False)),
                ('completion_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('started_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.lesson')),
                ('user_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='courses.usercourse')),
            ],
        ),
        migrations.CreateModel(
            name='LessonScore',
            fields=[
                ('scoreId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_scores_in_progress', to='courses.lesson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_scores', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
